In [18]:
import numpy as np 

In [19]:
x = np.array([True, True, True,False,True])
x

array([ True,  True,  True, False,  True])

In [20]:
n = 2
np.pad(x, (n, 0))[:-n]
np.pad(x, (0, n))[n:]


array([ True, False,  True, False, False])

In [75]:
import numpy as np

def print_matrix(matrix):
    # Determine the dimensions of the matrix
    rows, cols = matrix.shape
    
    # Print the header for the matrix
    col_nums = "    " + " ".join([f" {i+1:2}" for i in range(cols)])
    print(col_nums)
    row_divider = "   |" + "-" * (cols * 4) + "|"
    print(row_divider)
    
    # Print each row of the matrix
    for i in range(rows):
        row_string = " ".join([f"{num:3}" for num in matrix[i]])
        row_sum = f"{np.sum(matrix[i]):3}"
        print(f"{i+1:2} |{row_string} |{row_sum}")
    
    # Print the footer for the matrix
    col_sums = [f"{np.sum(matrix[:,j]):3}" for j in range(cols)]
    total_sum = f"{np.sum(matrix):3}"
    col_string = " ".join(col_sums)
    print(row_divider)
    print(f"   |{col_string} |")

    
# Create an 8x8 numpy array with random integers from 0 to 99
matrix = np.random.randint(low=-5, high=17, size=(8,8))
print_matrix(matrix)

      1   2   3   4   5   6   7   8
   |--------------------------------|
 1 |  3   2   2  -1   1   7   9  -1 | 22
 2 | -3   7   8  16   0  13   2  10 | 53
 3 |  4   9   8   8  15  -1  -1   0 | 42
 4 |  3   7   8  11  16   0  14  16 | 75
 5 | 15  -4   4  15   8  16   2  -5 | 51
 6 | 12  -4  14  15   3  16   8  15 | 79
 7 | 15   9   0   5  -5   1   9   5 | 39
 8 |  2   9   1  16   7  -1   1  11 | 46
   |--------------------------------|
   | 51  35  45  85  45  51  44  51 |


In [172]:
import numpy as np
from colorama import Fore, Style

def print_matrix(matrix, mask):
    # Determine the dimensions of the matrix
    rows, cols = matrix.shape

    # Print the header for the matrix
    col_nums = "    " + " ".join([f" {i+1:2}" for i in range(cols)])
    print(col_nums)
    row_divider = "   |" + "-" * (cols * 4) + "|"
    print(row_divider)

    # Print each row of the matrix
    for i in range(rows):
        row_items = []
        for j in range(cols):
            item = f"{matrix[i][j]:3}"
            if mask[i][j] == 1:
                item = f"{Fore.RED}{item}{Style.RESET_ALL}"
            elif mask[i][j] == 2:
                item = f"{Fore.GREEN}{item}{Style.RESET_ALL}"
            row_items.append(item)

        row_string = " ".join(row_items)
        row_sum = f"{np.sum(matrix[i]):3}"
        print(f"{i+1:2} |{row_string} |{row_sum}")

    # Print the footer for the matrix
    col_sums = [f"{np.sum(matrix[:,j]):3}" for j in range(cols)]
    total_sum = f"{np.sum(matrix):3}"
    col_string = " ".join(col_sums)
    print(row_divider)
    print(f"   |{col_string} |")
    
# Create an 8x8 numpy array with random integers from 0 to 99
matrix = np.random.randint(low=-5, high=17, size=(8,8))
mask = np.random.randint(low=0, high=3, size=(8,8))
print_matrix(matrix, mask)

      1   2   3   4   5   6   7   8
   |--------------------------------|
 1 | 12  -5   9   6  13   2   1   4 | 42
 2 | -4  -2  -2   7   0   5   2   1 |  7
 3 | 12   3  10  -1  -3   0   9   3 | 33
 4 |  7  16  -3   3   1  12   0   0 | 36
 5 | 10  13   2   5  -1   3   7  11 | 50
 6 | 11   9   7  16  10  16   4  12 | 85
 7 | 16  10   6   8   0   9  10  -4 | 55
 8 | -1   7  11   3  16  -5  -1  13 | 43
   |--------------------------------|
   | 63  51  40  47  36  42  32  40 |


In [194]:
def generate_nonzero_array(n: int):
    # Generate a 9x9 array with random integers between -20 and 20, excluding zero
    value_range = np.concatenate((np.arange(-20, 0), np.arange(1, 21)))
    arr = np.random.choice(value_range, size=(n, n))
    return arr

n = 4
grid = generate_nonzero_array(n)
mask = np.random.randint(low=1, high=3, size=(n, n))
included = grid * (mask == 2)
print(included.sum(axis=0))
print(included.sum(axis=1))
included

[-34   6 -13   4]
[-24 -40  27   0]


array([[-18,   0,  -6,   0],
       [-16, -11,   0, -13],
       [  0,  17,  -7,  17],
       [  0,   0,   0,   0]])